const fs = require('fs');
const path = require('path');

const dirPath = "c:\\Users\\Renato Sousa\\Desktop\\PJ\\veterinaria";
const files = ["stitch_home.html", "stitch_sobre.html", "stitch_contato.html", "stitch_especialidades.html"];

const animistaCSS = `<style id="animista-css">
/* ----------------------------------------------
 * Generated by Animista
 * ---------------------------------------------- */
.fade-in-bottom {
	-webkit-animation: fade-in-bottom 0.8s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
	        animation: fade-in-bottom 0.8s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}
@-webkit-keyframes fade-in-bottom {
  0% {
    -webkit-transform: translateY(50px);
            transform: translateY(50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    opacity: 1;
  }
}
@keyframes fade-in-bottom {
  0% {
    -webkit-transform: translateY(50px);
            transform: translateY(50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    opacity: 1;
  }
}
</style>
</head>`;

files.forEach(f => {
    const filePath = path.join(dirPath, f);
    try {
        let content = fs.readFileSync(filePath, 'utf-8');
        
        // 1. Remover link antigo do Animate.css com flexibilidade para espaços
        const animateRegex = /<link rel="stylesheet" href="https:\/\/cdnjs\.cloudflare\.com\/ajax\/libs\/animate\.css\/4\.1\.1\/animate\.min\.css"\s*\/>/g;
        content = content.replace(animateRegex, '');
        
        // Fallback apenas pegando o cdn se o de cima falhar
        if(content.includes('cdnjs.cloudflare.com/ajax/libs/animate.css')) {
            content = content.replace(/.*animate\.css.*/g, '');
        }

        // 2. Injetar animista
        if(!content.includes('id="animista-css"')) {
            content = content.replace('</head>', animistaCSS);
        }
        
        // 3. Modificar as classes de javascript da intersection
        content = content.replace(/'animate__animated',\s*'animate__fadeInUp'/g, "'fade-in-bottom'");
        
        fs.writeFileSync(filePath, content, 'utf-8');
        console.log(`[OK] Animista injetado em ${f}`);
    } catch(err) {
        console.error(`Falha em ${f}`, err);
    }
});
